project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://aulund.github.io/bloggen # you must change this appropriately for RSS feeds to work properly
  title: "August´s mbi-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true



